// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial1AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230313233345_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Books", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Emison")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Emison = new DateOnly(2000, 10, 1),
                            Precio = 2000.0,
                            Titulo = "Berserk Vol.1"
                        },
                        new
                        {
                            BookID = 2,
                            Emison = new DateOnly(2001, 10, 1),
                            Precio = 3000.0,
                            Titulo = "Berserk Vol.2"
                        },
                        new
                        {
                            BookID = 3,
                            Emison = new DateOnly(2002, 10, 1),
                            Precio = 4000.0,
                            Titulo = "Berserk Vol.3"
                        },
                        new
                        {
                            BookID = 4,
                            Emison = new DateOnly(2003, 10, 1),
                            Precio = 5000.0,
                            Titulo = "Berserk Vol.4"
                        },
                        new
                        {
                            BookID = 5,
                            Emison = new DateOnly(2004, 10, 1),
                            Precio = 6000.0,
                            Titulo = "Berserk Vol.5"
                        },
                        new
                        {
                            BookID = 6,
                            Emison = new DateOnly(2005, 10, 1),
                            Precio = 7000.0,
                            Titulo = "Berserk Vol.6"
                        },
                        new
                        {
                            BookID = 7,
                            Emison = new DateOnly(2006, 10, 1),
                            Precio = 8000.0,
                            Titulo = "Berserk Vol.7"
                        },
                        new
                        {
                            BookID = 8,
                            Emison = new DateOnly(2007, 10, 1),
                            Precio = 9000.0,
                            Titulo = "Berserk Vol.8"
                        },
                        new
                        {
                            BookID = 9,
                            Emison = new DateOnly(2008, 10, 1),
                            Precio = 10000.0,
                            Titulo = "Berserk Vol.9"
                        },
                        new
                        {
                            BookID = 10,
                            Emison = new DateOnly(2009, 10, 1),
                            Precio = 11000.0,
                            Titulo = "Berserk Vol.10"
                        },
                        new
                        {
                            BookID = 11,
                            Emison = new DateOnly(2022, 10, 1),
                            Precio = 12000.0,
                            Titulo = "Berserk Vol.11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
